SELECT
  ID
  ,USER_NAME
FROM
  USERS U
  INNER JOIN ITEMS I ON U.ID = I.BUYER_USER_ID
  LEFT JOIN ITEM_DETAILS ID ON I.ID = ID.ITEM_ID
WHERE
    U.ID > 10
AND I.TYPE IN (SELECT TYPE FROM M_ITEM WHERE ID > 50)
;